import { PERMISSIONS } from "./permission.js";
import { ROLES } from "./roles.js";

export const ACL = {
  [ROLES.ADMIN.id]: [
    PERMISSIONS.ADMIN_PANEL,
    PERMISSIONS.POST_CREATE,
    PERMISSIONS.POST_UPDATE,
    PERMISSIONS.POST_DELETE,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_UPDATE,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.REACTION_CREATE,
    PERMISSIONS.REACTION_DELETE,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.PROFILE_UPDATE
  ],

  [ROLES.MODERATOR.id]: [
    PERMISSIONS.POST_CREATE,
    PERMISSIONS.POST_UPDATE,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.REACTION_DELETE,
    PERMISSIONS.MESSAGE_SEND
  ],

  [ROLES.MEMBER.id]: [
    PERMISSIONS.POST_CREATE,
    PERMISSIONS.POST_UPDATE,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.REACTION_CREATE,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.COMMENT_UPDATE,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.REACTION_DELETE,
    PERMISSIONS.CONVERSATION_LIST,
    PERMISSIONS.CONVERSATION_CREATE
  ]
};
