import { PERMISSIONS } from "./permission.js";
import { ROLES } from "./roles.js";

// define permission sets once and reuse for both id and name lookups
const ADMIN_PERMS = [
  PERMISSIONS.ADMIN_PANEL,
  PERMISSIONS.POST_CREATE,
  PERMISSIONS.POST_UPDATE,
  PERMISSIONS.POST_DELETE,
  PERMISSIONS.COMMENT_CREATE,
  PERMISSIONS.COMMENT_UPDATE,
  PERMISSIONS.COMMENT_DELETE,
  PERMISSIONS.REACTION_CREATE,
  PERMISSIONS.REACTION_DELETE,
  PERMISSIONS.MESSAGE_SEND,
  PERMISSIONS.PROFILE_UPDATE
];

const MODERATOR_PERMS = [
  PERMISSIONS.POST_CREATE,
  PERMISSIONS.POST_UPDATE,
  PERMISSIONS.COMMENT_CREATE,
  PERMISSIONS.COMMENT_DELETE,
  PERMISSIONS.REACTION_DELETE,
  PERMISSIONS.MESSAGE_SEND
];

const MEMBER_PERMS = [
  PERMISSIONS.POST_CREATE,
  PERMISSIONS.POST_UPDATE,
  PERMISSIONS.COMMENT_CREATE,
  PERMISSIONS.REACTION_CREATE,
  PERMISSIONS.MESSAGE_SEND,
  PERMISSIONS.PROFILE_UPDATE,
  PERMISSIONS.COMMENT_UPDATE,
  PERMISSIONS.COMMENT_DELETE,
  PERMISSIONS.REACTION_DELETE,
  PERMISSIONS.CONVERSATION_LIST,
  PERMISSIONS.CONVERSATION_CREATE
];

export const ACL = {
  [ROLES.ADMIN.id]: ADMIN_PERMS,
  [ROLES.ADMIN.name]: ADMIN_PERMS,

  [ROLES.MODERATOR.id]: MODERATOR_PERMS,
  [ROLES.MODERATOR.name]: MODERATOR_PERMS,

  [ROLES.MEMBER.id]: MEMBER_PERMS,
  [ROLES.MEMBER.name]: MEMBER_PERMS
};
