import { CONNREFUSED } from "dns";

export const PERMISSIONS = {
  POST_CREATE: "POST_CREATE",
  POST_UPDATE: "POST_UPDATE",
  POST_DELETE: "POST_DELETE",

  COMMENT_CREATE: "COMMENT_CREATE",
  COMMENT_UPDATE: "COMMENT_UPDATE",
  COMMENT_DELETE: "COMMENT_DELETE",

  REACTION_CREATE: "REACTION_CREATE",
  REACTION_DELETE: "REACTION_DELETE",

  MESSAGE_SEND: "MESSAGE_SEND",
  CONVERSATION_LIST: "CONVERSATION_LIST",
  CONVERSATION_CREATE: "CONVERSATION_CREATE",

  PROFILE_UPDATE: "PROFILE_UPDATE",

  ADMIN_PANEL: "ADMIN_PANEL"
};

export const PERMISSION_LIST = Object.values(PERMISSIONS);
